package com.yantajenie.serviceProvider.services.SERVICES.Enums;

public enum Services {
    SCREEN,BATTERY,MIC,BACK_PANEL,PROXIMITY_SENSOR,CHARGING_JACK,AUX,FILTER_CHANGE,AC_CABINET_NOT_WORKING,AC_NOT_COOLING,CHANGE_GAS,DRAIN_CLEANING,COOLENT_LEVEL,OVER_ALL_INSPECTION,lAPTOP_MOTHER_BOARD_PROBLEM
    ,KEYBOARD,MOUSE,SPEAKER,LIGHT,TOUCHPAD,OS_PROBLEM,SOFTWARE_PROBLEM
}
